vanilla/docs

content/help/addons/social/facebook/index.md
content/help/addons/social/github/index.md
content/help/addons/social/googleplus/index.md
content/help/addons/social/index.md
content/help/addons/social/linkedin/index.md
content/help/addons/social/twitter/index.md
content/help/addons/social/zendesk/index.md

This fixes the issue where the social connection subpages don't appear under their parent in the navigation. 
Closes https://github.com/vanilla/vanilla/issues/4453

Fix parent identifiers, remove aliases and rename files

---

content/developer/theming/smarty/index.md
content/developer/theming/views.md

Update the link to the SmartyPlugins directory.

Update the link to the SmartyPlugins directory

---

content/help/sso/jsconnect/seamless.md

Updated this page:
http://docs.vanillaforums.com/help/sso/jsconnect/seamless/

Updated formatting to make the SSO page more readable

---

content/developer/importing/porter.md

Fixes https://github.com/vanilla/docs/issues/34

Improve documentation about redirects

---

content/developer/theming/css.md
content/developer/theming/hooks.md
content/developer/theming/smarty/conditionals.md
content/developer/theming/themeoptions.md
content/developer/theming/views.md

Remove array syntax and add info on setting layout options in $ThemeInfo.
Relies on https://github.com/vanilla/vanilla/pull/4979

Update theming docs

---

content/help/addons/social/twitter/index.md

the old one was not functioning any more...

updated URL

---

content/help/posting/smart-embed.md

Simple overview of smart embedding, I believe it covers all the methods

Add Smart Embed

---

content/developer/theming/views.md

Fix path to views in theming docs.

Fix path to views in theming docs

---

Gruntfile.js
README.md
config-dev.yaml

Since our APP’s unit tests use port 8080 it would be nice to not have
to worry about a clash. Also added a dev config because `npm run edit`
wouldn’t work for me without editing the the config.

Switch development version to port 8081

---

content/developer/framework/apiv2/api-endpoints.md
content/developer/framework/apiv2/authentication.md
content/developer/framework/apiv2/index.md
content/developer/framework/apiv2/resource-routing.md

Fix typos in API v2 docs

---

content/developer/theming/views.md

Just a simple broken link.
:beers:

Broken link in theming/views

---

content/developer/theming/themevisibility.md

New page to explain theme visibility

Added page on theme visibility

---

content/developer/theming/css.md

We don't want anybody overwriting the base styles anymore. It just creates support problems.

Removed section about overwriting base CSS

---

content/developer/theming/about-php.md
content/developer/theming/css.md
content/developer/theming/quickstart.md
content/developer/theming/themeoptions.md
content/developer/theming/themevisibility.md

Added info about making a custom theme to answer some FAQs.

Update to theming section

---

content/help/addons/pockets/index.md

Update the explanation for "repeat" to be more specific about its functionality.

Pockets Edit

---

content/help/analytics/advanced-analytics.md

Fixes https://github.com/vanilla/docs/issues/92
I fixed the bad merge and I added a lexicon to clarify certain terms.

Fix Advanced Analytic merge and add lexicon

---

content/apiv2/authentication.md
content/apiv2/index.md
layouts/apiv2/single.html
layouts/help/list.html
layouts/partials/menu/apiv2.html

These initial pages are pointed at from the dashboard.

Add some APIv2 docs

---

content/help/addons/advanced-editor/additional-settings.md
content/help/addons/advanced-editor/index.md

+additional settings. Needs the Posting doc before this goes live. Proof
reading that one next.

Advanced editor

---

content/help/posting/uploading-files.md

How to upload a file

---

content/help/multisite/sync.md

Fixes https://github.com/vanilla/docs/issues/110
Explain what the synchronization does and list what can be synchronized.

Add Hub sync description and details

---

README.md

Updated readme info regarding versioning in front-matter

Updated readme info regarding versioning in front-matter

---

content/developer/addons/addon-info.md
content/developer/vanilla-cli/build-process-v1.md
content/developer/vanilla-cli/build-quickstart.md
content/developer/vanilla-cli/bundling-process.md
content/developer/vanilla-cli/index.md

For after https://github.com/vanilla/vanilla-cli/pull/37 goes through.

Add docs about less stylesheet compilation

---

content/developer/addons/addon-info.md
content/developer/vanilla-cli/build-process-v1.md
content/developer/vanilla-cli/build-quickstart.md
content/developer/vanilla-cli/bundling-process.md
content/developer/vanilla-cli/index.md

Revert "Add docs about less stylesheet compilation"

---

content/help/reputation/ranks/adding-and-editing-ranks.md

deleted a phrase that no longer applies to the current functionality of the product

Update adding-and-editing ranks

---

content/api/badges/index.md

Updated the API Call for Badges/give
Changed User to UserID
Changed the call from badges/giveuser to badge/giveuser

fixed badges-give parameters

---

static/js/swagger/swagger-data.json

Close #179 
Updates the swagger data

Update swagger data

---

content/developer/smarty/index.md

Update links in smarty index

---

content/developer/addons/addon-info.md
content/developer/vanilla-cli/build-process-core.md

I've updated the docs to reflect the changes in https://github.com/vanilla/vanilla-cli/pull/60.

Update docs with changes from core build process

---

content/help/posting/index.md

This list was formatted incorrectly. I've adjusted it to be a markdown list.
Closes #139

Fix numbered list styling

---

content/developer/apiv2/resource-routing.md
content/developer/framework/controllers.md
content/developer/framework/views.md
content/help/analytics/index.md
content/help/reputation/ranks/index.md
content/help/reputation/reactions/index.md
content/help/sso/jsconnect/index.md

Closes #207 
In addition I found some other 404 pages by looking through the site's access logs.

Fix broken links

---

content/help/forum-settings/categories/index.md

Added details about the new category following feature.

Add documentation for Category Following

---

content/help/ideation/index.md

Add alias to ideation

---

content/api/users/index.md

Parameters Changed
User -->UserID
Picture-->Avatar

Update uploading a user photo with API v1

---

README.md

Adds hugo version information to README. I've linked to hugo release page of the proper version.

Add hugo version info to README

---

content/api/index.md
content/api/moderation/index.md

- Update authentication information for the API v1.
- Rename Simple API to API v1 in the docs.

Update authorization information for the API v1

---

content/help/embedding/index.md

Closes #226
This link never actually existed, and made it through accidentally when trying to resolve where this would actually go.

Remove bad link

---

content/developer/changelog/index.md
content/developer/configuration/index.md
content/developer/framework/controllers.md
content/developer/framework/datasets.md
content/developer/importing/porter.md
content/help/reputation/badges.md
content/help/reputation/ranks.md
content/help/sso/index.md
content/help/sso/jsconnect.md

"Thru" was used quite often instead of "through"

Replace "thru" with "through"

---

build/scss/components/_privacyBanner.scss
build/scss/globals/_docs.scss
build/scss/globals/_variables.scss
build/scss/globals/mixins/_mixin.mediaQueries.scss
static/css/docs.css

These are styles for the new privacy banner.
Related: https://github.com/vanilla/vanillaforumscom/pull/123

Styles for privacy banner

---

content/developer/troubleshooting/sso.md

Closes https://github.com/vanilla/internal/issues/1555

Add SSO troubleshooting section

---

content/developer/framework/inform.md
content/developer/framework/modules.md

Closes #249
Closes #209
Closes #195 
Converts all HTML to Markdown on those pages:
https://docs.vanillaforums.com/developer/framework/inform/
https://docs.vanillaforums.com/developer/framework/modules/

Convert pages from .html to .md

---

content/developer/troubleshooting/index.md

Per our discussion in huddle this morning.
This page is what is linked from our core README.
(Merging this PR will rebuild the docs, which should be live in ~10 minutes.)

Improve troubleshooting steps for installs

---

content/developer/contributing/security-standards.md

I've added a document outlining how to prevent XSS while coding views in javascript and PHP. I'm sure we will be expanding this document to cover other security concerns in the future such as CSRF and permission checking.

Add secure coding guide with XSS details

---

content/help/appearance/custom-theme.md

Related [#292](https://github.com/vanilla/vanilla-patches/issues/292)

CustomizeTheme: added a note to safely implement smarty

---

content/developer/tools/environment.md

Fix bad git hooks instructions

---

content/developer/addons/events-and-handlers.md

Closes https://github.com/vanilla/docs/issues/311

Fix typo in event handler example

---

content/developer/framework/feature-flags.md

This update introduces developer usage details for feature flags.

Add feature flag docs

---

content/developer/tools/building-frontend.md

Documents the changes from https://github.com/vanilla/vanilla/pull/7738
- New output file location.
- Custom entry files.
- Where to get your output file paths from.
- composer post-install script and environmental variables

Update build tool documentation

---

content/help/apiv2/smart-ids.md

Here, we're adding documentation on using smart IDs in API v2.
Closes #317

Add docs page for using smart IDs in API v2

---

content/help/embedding/index.md

I got these instructions with @nervoustwit earlier today. Thought it would be a good idea to update the docs with those as it might help someone in the future.

add instructions for testing embedding

---

content/help/addons/hero-image.md

Hero Image now included in open-sourced Vanilla

---

content/help/releases/2019-004.md
content/help/releases/index.md

2019.004 release notes

---

content/help/releases/2019-004.md
content/help/releases/2019-005.md

This PR will add the release notes for the 2019-005 release.

Add release notes for 2019-005.

---

content/help/addons/salesforce.md

Closes https://github.com/vanillaforums/zte/issues/33
TLDR: Salesforce integration that sync Vanilla users with Salesforce contacts on user edit profile/registers.
Estimate: https://github.com/vanillaforums/estimates/blob/master/zte/ZTE%20-%20Salesforce%20Integration%20Estimate.md
Related PRs:
https://github.com/vanilla/internal/pull/1845
https://github.com/vanilla/vanilla/pull/8745
https://github.com/vanilla/docs/pull/344

add salesforce integration docs

---

content/developer/addons/addon-quickstart.md
content/developer/addons/creating-new-functionality.md
content/developer/addons/events-and-handlers.md
content/developer/addons/plugin-theme-info.md

Reading through the documentation, ran across a nonsense sentence. Pretty sure it is correct now.

Fix nonsense sentence

---

content/developer/smarty/index.md

related https://github.com/vanilla/vanilla-patches/issues/661
I've added a note for when using smarty's debug feature, it should be turned off as it discloses personal information.

[Smarty] add a note to smarty debug feature
