content/developer/framework/oauth.md
content/help/sso/oauth/index.md

Up until now our OAuth doc only told users that they could connect to third-party providers using OAuth2. We have since added a base class which developers can extend to build custom OAuth plugins. We have also added our own OAuth2 plugin that can be used to create SSO connections "out of the box".
This pull request updates the help docs giving an overview, the assumptions, and features of the plugin.

Update OAuth help doc to include OAuth2 plugin

---

content/developer/backend/index.md
content/developer/changelog/index.md
content/developer/community/index.md
content/developer/contributing/index.md
content/developer/contributing/pull-requests.md
content/developer/framework/index.md
content/developer/importing/index.md
content/developer/importing/porter.md
content/developer/importing/support.md
content/developer/locales/index.md
content/developer/plugins/quickstart.md
content/help/cloud/leaving/index.md
content/help/cloud/support/index.md

I've replaced links going to the old community forum (vanillaforums.org) to the new address (open.vanillaforums.com) and changed some wording where necessary, mainly "VanillaForums.org" => "community forum"

Update links from vanillaforums.org to open.vanillaforums.com

---

content/developer/importing/support.md

The forum module for Joomla is called [Kunena](https://extensions.joomla.org/extension/kunena/) and the drupal forum module which is support by the porter is [Advanced Forum](https://www.drupal.org/project/advanced_forum)

Fix typo for "Kunena" and add more info to "Drupal Forum"

---

content/help/sso/jsconnect/overview.md

I was not able to find notes about using the expanded /entry/jsconnect endpoint in the current docs.

Add notes about non-default seamless endpoint

---

content/developer/framework/apiv2/api-endpoints.md
content/developer/framework/apiv2/resource-routing.md

This update fixes some syntax and formatting issues, in addition to correcting some class names.

Fix formatting and class names in API v2 docs

---

content/developer/backend/index.md

This update adds a blurb to the Backend page on how to use `bootstrap.before.php` to overwrite values in the `$_SERVER` superglobal, particularly in regard to incoming headers used to set the host.

Add section on advanced header handling to Backend page

---

content/help/addons/vanilla-pop/index.md

Image URI was relative, the document was moved to a directory and the image was coming up not found. This PR will fix that .

Fix address to missing image on VanillaPop page in Help

---

README.md
content/developer/locales/index.md

After receiving a request for more information about multilingual overrides I've updated the docs on locales with that information.

Update locales documentation with details about multilingual overrides.

---

content/developer/framework/modules.md

The example in the module documentation extends the incorrect class and does not run. It should be `Gdn_Module` instead of `Module`.

Fix Gdn_Module example

---

content/help/addons/mailchimp-push/index.md

When loading docs locally, the help index loads incorrectly, so please check that before/after pushing this

Mailchimp Push doc

---

Gruntfile.js
config-dev.yaml

Links being generated in local development were not correct. The `baseUrl` was getting set to nothing in the config file, and not being properly overridden by the command line flag. The `buildDrafts` flag was also being set in the `config-dev.yaml` so the extra flag being pushed into the args wasn't working properly. 
After this links generated on localhost are now the correct links.

Fix broken links in local development

---

content/developer/contributing/coding-standard.md

Update the Coding Standard section.
Update PHP Version section's information.
Link to the correct repository for code-sniffer standards.

Update "PHP Version" and "CodeSniffer" sections

---

layouts/partials/footer/copyright.html

Pages don’t have a Now property anymore, but there is a now template
function.

Fix deprecation warning regarding the now variable

---

content/developer/changelog/index.md
content/help/addons/salesforce/index.md
content/help/moderation/reporting/index.md
content/help/releases/2017.md
content/help/sso/saml/index.md

I noticed that using “->” for some arrows looks quite ugly.

Replace arrows with unicode characters

---

content/developer/addons/addon-info.md

"registerPermissions" and "authors" both had incorrect examples. This PR corrects them.

Correct examples in the Addon Info docs page.

---

static/js/search.js

The doubled search results were bothering me so I did a quick look and it seems we were cloning an existing search result element with jquery, but since we made the page responsive it would be cloned twice. I've fixed the issue by grabbing the first `searchResult` instead of all of them as a template.

Fix doubled search results

---

content/developer/locales/index.md

I noticed subcommunities weren't mentioned in the multilingual docs so I added them.

Add subcommunities to mutlilingual docs

---

content/developer/addons/addon-info.md
content/developer/vanilla-cli/index.md

Adds documentation about the `vanilla lint` command in the CLI and its addon.json configuration options.
On hold until the functionality is merged into the CLI.

Add documentation about linting command

---

content/api/badges/index.md

Giving a badge using the API would need to call  /api/v1/badges/giveuser.json instead of  /api/v1/badges/give.json

Fixed Badge give user API Call

---

content/developer/addons/addon-info.md
content/developer/vanilla-cli/build-process-core.md
content/developer/vanilla-cli/build-process-v1.md
content/developer/vanilla-cli/index.md
content/developer/vanilla-cli/installation.md

Closes #177, #176, #162 
This PR adds documentation about the core build process, including it's new methods of bundling, and child theme support.
I've also added an installation guide for the build tool.

Add core build process info and installation guide

---

content/developer/framework/apiv2/unified-record-format.md

This update adds the "unified record format" page, which documents a couple things:
1. Dictates fields that should be included when API responses include multiple resource types. 
1. Lists out "common" fields, and descriptions, endpoints should strive to use, if applicable to columns in their resource type.

Add Unified Record Format page

---

content/help/addons/social/github/index.md

Move the addon social integration with the other addons

Add alias for broken Github docs link in internal repo

---

content/help/addons/advanced-editor/index.md

Fix link to Advanced settings of Advanced Editor (original link leads to a 404 page).

Fix broken advanced editor link

---

content/developer/smarty/functions.md

Closes #157
Adds advanced searchbox documentation to the smarty docs. I've cross-linked the help docs on advanced search as well.

Add {searchbox_advanced} smarty function docs.

---

content/developer/addons/events-and-handlers.md
content/developer/addons/index.md
content/developer/addons/theme-hooks.md
content/developer/addons/view-overrides.md
content/developer/framework/controllers.md
content/developer/smarty/functions.md

Closes #201 
I've added back the old example and a lot of additional ones. I also refreshed most of the links. I moved the redirects from the old themehooks page that were on the events and handlers page to the new themehooks page.

Add back themehooks docs with additional examples

---

content/apiv2/index.md

Fixes https://github.com/vanilla/vanilla/issues/6069
Explain APIv2 pagination
- Header links
- Variable number of results / empty pages
- Numbered vs More pagination type

Add pagination section to APIv2 doc

---

content/help/sso/index.md
content/help/sso/jsconnect/index.md

Fixes https://github.com/vanilla/docs/issues/95
Add explanation about:
- Account connection
- AutoConnect feature
- Magic `{target}` value
Put more emphasis on some details like information validity (especially emails).

 Expand the SSO General principles section

---

content/apiv2/index.md

Fixes https://github.com/vanilla/docs/issues/213
I decided not to create a dedicated section for "Link header" for now since there's only pagination using it. We can refactor the doc appropriately if that ever changes.

Add pagination section to APIv2 documentation

---

static/js/swagger/swagger-ui-plugin.js

Closes https://github.com/vanilla/vanilla-patches/issues/179
Apparently swagger allows any configuration variable to be overridden through a query parameter and currently has no way to disable this functionality. 
I've opened an issue here https://github.com/swagger-api/swagger-ui/issues/4332 and have added a bit of javascript to strip off query parameters before loading swagger-ui. It's not the perfect solution, but there is not much else we can do here without forking/upstreaming a fix into swagger-ui. I'm open to doing that, but want to make sure it would be accepted first.

Fix swagger query config injection

---

content/developer/addons/theming-modules.md

The new `theming-modules.md` page is intended to contain the documentation for multiple modules. I'm starting with just the Group Search Module.
Also note the `/feature/group-search` branch might get more information when we add the back-end functionality for the group search.

Added "Group Module" section to "Theming Modules" page

---

content/developer/vanilla-cli/build-process-core.md
content/developer/vanilla-cli/bundling-process.md
current-links.json

Closes #252 
- Documents the * exports key
- Documents typescript support. This PR is just covering the build tooling part of the support. Our typescript conventions intro, etc will come in a later PR.

Update build tool documentation

---

content/developer/addons/events-and-handlers.md
content/developer/apiv2/authentication.md
content/developer/changelog/index.md
content/developer/configuration/using.md
content/developer/framework/assets.md
content/developer/framework/controllers.md
content/developer/framework/database.md
content/developer/framework/datasets.md
content/developer/framework/inform.md
content/developer/framework/models.md
content/developer/framework/modules.md
content/developer/framework/permissions.md
content/developer/framework/requests.md
content/developer/framework/views.md
content/developer/tools/environment.md
content/developer/troubleshooting/index.md

Also fixes obvious code typos (wrong parenthesis or wrong variable referenced).
This should fix https://github.com/vanilla/docs/issues/262

Fix Variable, Method And Function Names To Start With Lower Case Letters

---

content/developer/embeds/index.md

This update adds docs for the basics of creating a new site embed.
Closes vanilla/vanilla#7215

Add developer docs on embeds

---

content/developer/embeds/index.md

A few things that I actually noticed right after I merged the initial PR and things to keep in mind for future docs.
- More tags are needed
- An alias is a redirect. It's a totally new page so we don't need it.
- If you make the first title of the page the same as the main page title, it shows up twice (The page title shows up right above the page.)
- The title is kind of overloaded with our embedding docs, so I adjusted it to make it a little bit more clear.

Tweaks to embed doc metadata

---

content/developer/changelog/index.md

Closes https://github.com/vanilla/vanilla/issues/5171
Details are copied directly from release notes.
- Adds releases 2.4 -> 2.6
- Adds a few highlights about each release.
- Updates the heading structure to make use of the doc sidebar.

Update change log

---

content/developer/contributing/coding-standard-php.md
static/documents/VanillaPHPStormCodingStyle.xml

Closes https://github.com/vanilla/docs/issues/190
I've updated the docs for our PHP standards so that people can conform to our standard more easily.
- Specific CodeSniffer version installation instructions (with composer instead of PEAR).
- PHPStorm CodeSniffer instructions.
- Command Line CodeSniffer instructions.
- PHPStorm Code Style XML download.

Add greater detail to validation section of PHP Coding Standards docs

---

content/developer/contributing/coding-standard-php.md

We are now working with PHPCS 3.
https://github.com/vanilla/standards/pull/15

Update phpcs version installation instructions 

---

content/developer/addons/addon-quickstart.md

The word "permission" was missing

Fix Typo in addon-quickstart

---

content/help/sso/steamconnect.md

Closes [#647](https://github.com/vanilla/addons/issues/647)
Adds an overview document on SteamConnect plugin.

Add SteamConnect documentation

---

content/developer/smarty/functions.md
content/help/addons/hero-image.md

The documentation had the wrong smarty tag to fetch the hero image url.

Fixed documentation on Hero Image Plugin

---

content/developer/contributing/coding-standard-php.md

A few changes here:
- New global function declarations are forbidden.
- Method doc block standard has been updated to reflect what is currently enforced by CodeSniffer as of https://github.com/vanilla/standards/pull/28
- Method naming exceptions have been documented to be consistent with `ResourceRoute` and and its controllers and our standards enforcement as of https://github.com/vanilla/standards/pull/29

Update PHP coding standard

---

content/help/getting-started/custom-domain.md

Changes "redirects" to "forwards" to avoid any confusion.
Put emphasis on SEO problems caused by using subfolder.

Clarification and emphasis

---

content/developer/contributing/database-naming-standards.md
yarn.lock

Database naming standards are changing in Vanilla. Here, we document how and why.
Also, there was a node module that needed updating (node-sass), due to incompatibility with newer versions of other modules. Functionality should be unaffected.
Closes #319

Add database naming standards doc

---

content/help/apiv2/analytics.md

Running an analytics/query with the following body returns some users with user.userID = -1
This was a result of https://github.com/vanilla/analytics/pull/223 that set userid to -1 for users in Europe to be GDPR compliant.
I added a small line to explain this in the docs.
{
"type": "count",
"collection": "page",
"start": "2018-12-12",
"end": "2018-12-13",
"property": "",
"filters": [
{"prop": "type", "op": "eq", "val": "page_view"}
],
"interval": "daily",
"group": "user.userID"
}

APIV2 analytics/query : add line to explain user.userID=-1 that was added for GDPR compliance

---

content/developer/addons/theme-options.md

Following https://github.com/vanilla/vanilla/pull/7960 the global `touchConfig` method is deprecated.
PR replacing usages in core: https://github.com/vanilla/vanilla/pull/8203
This PR updates `touchConfig` usage to be `Gdn::config()->touch()` instead.

Replace touchConfig usage

---

content/developer/apiv2/api-endpoints.md

The link to "resource routing" in the "writing api enpoints" document is wrong and gives a 404. This PR corrects that link

Fix link from "writing api endpoints" to "resource routing"

---

content/help/sso/social-connect.md

We are replacing Google + Social Sign In with Google Sign In. This causes us to need to update our public facing docs for instructions on how to configure it.
This PR removes references to Google +, adds instructions to Google Sign In.
This PR closes #https://github.com/vanilla/vanilla/issues/8643

Update the help docs to replace Google + with Google Sign In instructions.

---

content/developer/addons/addon-info.md

Section Priority
Typo:
"Addons use a priority system to determine which order they load in. The higher the priority an addon has, the later in the process it loads. Avoid using this is you can."
Change to:
"Addons use a priority system to determine which order they load in. The higher the priority an addon has, the later in the process it loads. Avoid using this if you can.

addon-info.md - change is > if

---

content/help/analytics/advanced-analytics.md

Add a line to further explain how active users are calculated.
Related [#106](https://github.com/vanilla/support/issues/106)

Advanced Analytics: add line further explaining active-users calculation

---

content/help/apiv2/analytics.md

closes [#427](https://github.com/vanilla/support/issues/427)
We do not have "top-positive-users" &  "top-member-by-accumulated-reputation" as a board parameter when making a call to [/api/v2/analytics/leaderboard](https://docs.vanillaforums.com/help/apiv2/analytics/#leaderboards).
[class.keeniotracker.php#L36](https://github.com/vanilla/analytics/blob/master/plugins/vanillaanalytics/models/class.keeniotracker.php#L36)

Analytics: Update board parameters doc when making a call to /api/v2/analytics/leaderboard

---

content/developer/addons/addon-quickstart.md

We removed the example because it was very outdated in its coding practices.
Closes #346

Remove the example addon from our docs

---

content/developer/addons/adding-new-embeds.md

A new how-to with example code has been added for creating new embed types in the React-based embed system using addons.
Do not merge until vanilla/vanilla#9002 has been merged.

Add docs for new React-based embed components

---

content/help/addons/salesforce.md

Users were confused by the name "SalesforceID". I tried to make more clear with the actual name in salesforce and images.

Add more details to the Profile Extender integration docs
